name: Ping Runner
on:
  workflow_dispatch:
jobs:
  ping:
    runs-on: self-hosted
    steps:
      - run: |
          echo "Runner picked this job ✅"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          echo "Labels are ignored now (self-hosted only)"
          docker version
